

- name: Make sure tgz is absent
  file:
    path: /opt/cerebro-{{elastic_cerebro_version}}.tgz
    state: absent

- name: Download lmenez/cerebro
  uri:
    url: https://github.com/lmenezes/cerebro/releases/download/v{{elastic_cerebro_version}}/cerebro-{{elastic_cerebro_version}}.tgz
    dest: /opt/cerebro-{{elastic_cerebro_version}}.tgz
    mode: 0740

- name: Pid file
  file:
    path: /var/run/cerebro/
    state: directory
    owner: "{{ cerebro_user }}"
    group: "{{ cerebro_group }}"
    mode: '755'

- name: Create program folder
  file:
    path: "/opt/cerebro-{{elastic_cerebro_version}}"
    state: directory
    owner: "{{ cerebro_user }}"
    group: "{{ cerebro_group }}"
  notify:
    - restart elastic-cerebro

- name: Extract tarball
  unarchive:
    remote_src: yes
    src: "/opt/cerebro-{{elastic_cerebro_version}}.tgz"
    dest: "/opt/"
    owner: "{{ cerebro_user }}"
    group: "{{ cerebro_group }}"
  notify:
    - restart elastic-cerebro

- name: Replace java version check to support version 11
  lineinfile:
    path: "/opt/cerebro-{{elastic_cerebro_version}}/bin/cerebro"
    regexp: '^  readonly java_version'
    line: 'return'
  notify:
    - restart elastic-cerebro
  tags: "elastic:cerebro:ver"

- name: Template out the configuration
  template:
    src: application.j2
    dest: /opt/cerebro-{{elastic_cerebro_version}}/conf/application.conf
  tags: "elasticsearch-cerebro:config"
  notify:
    - restart elastic-cerebro

- name: Template out the service file
  template:
    src: cerebro_service.j2
    dest: /etc/systemd/system/cerebro.service
  notify:
    - restart elastic-cerebro


- name: Ensure service is started
  service:
    state: started
    name: cerebro
